#g++ -o zadania -I ./headers
#g++ -c -o main.o ./sources/main.cpp
g++ -std=c++11 -c -o ./object/Name.o ./sources/Name.cpp
g++ -std=c++11 -c -o ./object/Resistor.o ./sources/Resistor.cpp
g++ -std=c++11 -c -o ./object/main.o ./sources/main.cpp
g++ -std=c++11 -I ./headers -Wall -O -g -o zadania.exe ./object/main.o ./object/Name.o ./object/Resistor.o -lm

echo "============================================================"
#Wywolanie programu
#./zadania.exe
